---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane-openstack-config
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: crossplane-openstack-config
                addonChartVersion: main
                addonChartRepository: https://github.com/uwej711/crossplane-openstack-config.git
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: main
          - clusters:
              selector:
                matchLabels:
                  environment: production
              values:
                addonChartVersion: main
  template:
    metadata:
      name: '{{.values.addonChart}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.values.addonChartRepository}}'
          path: '.'
          targetRevision: '{{.values.addonChartVersion}}'
      destination:
        namespace: crossplane-system
        name: '{{.name}}'
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            access-cluster-secrets: "true"
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
