apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bws-k8s-keystone-auth
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: bws-k8s-keystone-auth
                # anything not staging or prod use this version
                addonChartVersion: 0.1.1
                addonChartRepository: https://valiton-k8s-blueprints.github.io/charts
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: 0.1.1
          - clusters:
              selector:
                matchLabels:
                  environment: production
              values:
                addonChartVersion: 0.1.1
  template:
    metadata:
      name: '{{.values.addonChart}}'
      annotations:
        argocd.argoproj.io/compare-options: IncludeMutationWebhook=true
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - repoURL: '{{.values.addonChartRepository}}'
          chart: '{{.values.addonChart}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{.metadata.annotations.applications_repo_path}}/config/{{.values.addonChart}}/values.yaml
              - $values/{{.metadata.annotations.applications_repo_path}}/config/{{.values.addonChart}}/{{.metadata.labels.environment}}.yaml
            values: |
              authUrl: {{.metadata.annotations.openstack_auth_url}}
      destination:
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
